baseURL: "https://seaman.eng/"
title: Ned Seaman
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
pygmentsUseClasses: true

minify:
    disableXML: true
    minifyOutput: true

taxonomies:
    tag: tags
    hobby: hobbies

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Ned Seaman
    description: "A personal website for Ned Seaman"
    keywords: [Blog, Portfolio]
    author: Ned Seaman
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    label:
        text: "\U0001F4A5 Ned Seaman \U0001F4A5"

    # home-info mode
    homeInfoParams:
        Title: "Hi there! My name is Ned."
        Content: "I'm earning my bachelor's in **computer science** and **financial engineering** from WashU in St. Louis. I'm passionate **software engineering**, **music**, **board games**, and a host of other topics. Feel free to contact me or explore some of my hobbies!"

    socialIcons:
        - name: linkedin
          url: "https://linkedin.com/in/ned-seaman/"
        - name: github
          url: "https://github.com/nedseaman/"
        - name: email
          url: "mailto:n.m.seaman@wustl.edu"
        - name: cv
          url: "/Ned_Seaman_Resume_Updated.pdf"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: hobbies
          name: Hobbies
          url: /hobbies/
          weight: 20
        - identifier: tags
          name: Tags
          url: /tags/
          weight: 30
        - identifier: search
          name: Search
          url: /search/
          weight: 40
        - identifier: archive
          name: Archive
          url: /archives/
          weight: 50
